import { useEffect, useMemo, useState } from "react";
import { LanguageContext, useLanguage } from "./language-context";
const LANGUAGE_STORAGE_KEY = "myclim-language";
const supportedLanguages = ["en", "fr", "de"];

const messages = {
  en: {
    myclim: "MyCLIM",
    returnHome: "Back to home",
    loginPageTitle: "MyCLIM Volunteer Space",
    loginPageSubtitle: "Sign in to view your assignments, documents, accreditation, and all useful meeting information.",
    loginEyebrow: "Sign in",
    loginHeading: "Access MyCLIM",
    loginEmailLabel: "Email",
    loginPasswordLabel: "Password",
    loginForgotPassword: "Forgot password",
    loginForgotPasswordLoading: "Sending...",
    loginRememberMe: "Remember me",
    loginRememberMeDescription: "Stay signed in on this device after closing the browser.",
    loginButton: "Sign in",
    loginLoading: "Signing in...",
    loginError: "Sign in failed. Please check your email and password.",
    loginResetSuccess: "If an account exists for this address, a reset email has just been sent.",
    loginResetError: "Unable to send the reset email at this time.",
    loginResetEmailRequired: "Please enter your email address first to receive the reset link.",
    loginVolunteerLink: "Become a volunteer",
    loginPreprogramLink: "Register a child for the pre-programme",
    landingTopline: "CMCM Luxembourg Indoor Meeting",
    landingTitle: "MyCLIM - Everything you need for the CMCM Luxembourg Indoor Meeting 2027",
    landingDescription:
      "Choose your path to access registrations, practical information, and your personal space.",
    landingLoginButton: "Log in",
    landingLoginHint: "Already have an account? Access your personal space directly.",
    volunteersTitle: "Volunteers",
    volunteersDescription: "Sign in, create an account, or apply as a volunteer.",
    preprogramTitle: "U12/U14 Pre-Program",
    preprogramDescription: "Parent access and registration for the pre-program and basket carriers.",
    volunteerPageTitle: "CMCM Luxembourg Indoor Meeting Volunteers",
    volunteerPageSubtitle: "Sign in to your space or submit your volunteer application.",
    volunteerLoginEyebrow: "Sign in",
    volunteerLoginTitle: "I already have an account",
    volunteerLoginDescription: "Sign in to view your assignments, documents, and meeting information.",
    volunteerApplyEyebrow: "Application",
    volunteerApplyTitle: "I want to volunteer",
    volunteerApplyButton: "Apply now",
    volunteerCloseButton: "Close form",
    volunteerPlaceholder: "The volunteer form will appear here, just below this section.",
    preprogramPageTitle: "U12/U14 Pre-Program and Basket Carrier Registration",
    preprogramPageSubtitle:
      "Register your child for the U12/U14 pre-program or the basket carrier role, then follow updates in your parent space.",
    preprogramIntroEyebrow: "U12 / U14 2027",
    preprogramIntroTitle: "Register my child for the pre-program or as a basket carrier",
    preprogramIntroDescription:
      "The parent account is created during registration. For each child, you can indicate whether they would like to join the pre-program, be a basket carrier, or be considered for either option depending on availability.",
    preprogramClosedTitle: "Registrations open on November 10, 2026 at 10:00 AM",
    preprogramClosedDescription:
      "The pre-program and basket carrier form is not open yet. Until then, this page explains how selections and confirmations will work.",
    preprogramClosedCardTitle: "How selections work for the 2027 edition",
    preprogramClosedCardBody:
      "For the 2027 edition, your child's application will only be reviewed if the file is complete. For the races, places are allocated in the order complete applications are received, then a waiting list applies once capacity is reached. On meeting day, each child can only be confirmed for one activity. If you request both the pre-program and the basket carrier role, the final confirmation will be given for only one of the two options.",
    preprogramClosedRulesTitle: "Important rules to know before opening day",
    preprogramClosedRulesBody:
      "Each child can only be confirmed in one activity on the day of the meeting. If a request is submitted for both the pre-program and basket carrier role, the final confirmation will only be given for one of them.",
    preprogramClosedTimingTitle: "What happens on opening day",
    preprogramClosedTimingBody:
      "On November 10, 2026 at 10:00 AM, the form will automatically become available on this same page. You will then be able to create the parent account and submit the request.",
    fieldFirstName: "First name",
    fieldLastName: "Last name",
    fieldGender: "Gender",
    fieldSelectPlaceholder: "Select",
    genderFemale: "Female",
    genderMale: "Male",
    otherLabel: "Other",
    fieldTshirtSize: "T-shirt size",
    fieldEmail: "Email",
    fieldPhone: "Phone",
    fieldPassword: "Password",
    fieldConfirmPassword: "Confirm password",
    fieldBirthDate: "Date of birth",
    under14Title: "Under 14",
    under14Body:
      "Sorry, we unfortunately cannot accept volunteers under 14, except for the basket carrier role, subject to availability.",
    minorTitle: "Underage volunteer",
    minorBody:
      "Your date of birth indicates an underage volunteer. A legal guardian contact is mandatory and will need to approve it by email.",
    adultTitle: "Adult application",
    adultBody: "You can continue with the standard volunteer application.",
    createParentAccountLink: "Create a parent account",
    guardianEyebrow: "Legal guardian",
    guardianHeading: "Mandatory approval for ages 14-17",
    guardianFirstNameLabel: "Legal guardian's first name",
    guardianLastNameLabel: "Legal guardian's last name",
    guardianEmailLabel: "Legal guardian's email",
    guardianPhoneLabel: "Legal guardian's phone",
    languagesEyebrow: "Languages",
    languagesHeading: "Which languages do you speak?",
    otherLanguageLabel: "Other language",
    lunexEyebrow: "LUNEX",
    lunexHeading: "Are you a LUNEX student?",
    yesLabel: "Yes",
    noLabel: "No",
    lunexProgramLabel: "LUNEX programme",
    occupationLabel: "Occupation",
    cmcmExperienceLabel: "Experience at the CMCM Luxembourg Indoor Meeting",
    otherVolunteerExperienceLabel: "Other volunteer experience",
    availabilityEyebrow: "Availability",
    availabilityHeading: "When are you available?",
    availabilityIntro:
      "Morning briefings are mandatory. For the meeting, we need volunteers available on Sunday 17/01/2027 from 9:30 AM to 7:00 PM. Exact times will be confirmed later, but this window should be considered essential for meeting day. Any help before the event is welcome, and we would be especially grateful for help available on Monday.",
    mandatorySundayTitle: "Sunday 17/01/2027 mandatory",
    mandatorySundayBody:
      "Availability required for the briefing, the pre-meeting snack, doors opening at 1:00 PM, and the competition from 4:00 PM to 7:00 PM.",
    confirmSundayLabel: "I confirm I am available on Sunday 17/01/2027",
    confirmSundayBody:
      "I understand that my presence from approximately 9:30 AM to 7:00 PM, briefing included, is essential for meeting day.",
    availabilitySubnote:
      "You can also let us know below if you're available to help before the meeting or with the Monday clean-up.",
    availabilityFridayMorning: "Pre-meeting - Friday morning",
    availabilityFridayAfternoon: "Pre-meeting - Friday afternoon",
    availabilitySaturdayMorning: "Pre-meeting - Saturday morning",
    availabilitySaturdayAfternoon: "Pre-meeting - Saturday afternoon",
    availabilityMondayAfterMeeting: "Post-meeting - Monday 9 AM-12 PM",
    missionPreferencesEyebrow: "Mission preferences",
    missionPreferencesLabel: "Which missions would you like to help with?",
    missionPreferencesHint:
      "You can select several. This tells us what you'd like to do, but it doesn't guarantee you'll get one of these missions — the team assigns roles based on the event's actual needs.",
    missionPreferencesUnavailable: "The list of missions isn't available yet — you'll be able to indicate your preferences later from your volunteer space.",
    healthSafetyLabel: "Health / safety information",
    nextEditionTitle: "Next edition",
    nextEditionBody: "I agree to be contacted about the next edition.",
    imageRightsTitle: "Image rights",
    imageRightsBody:
      "Attending the event involves photo and video coverage in the meeting areas. Without your agreement on this point, we unfortunately cannot accept your application.",
    rgpdDisclaimer:
      "By submitting this form, you agree that your personal data will be processed by the Luxembourg Athletics Federation solely for the purpose of your registration, your participation in the CMCM Luxembourg Indoor Meeting, and related communications.",
    submitApplicationButton: "Submit my application",
    submittingLabel: "Sending...",
    errorPasswordMismatch: "The two passwords do not match.",
    errorSundayConfirmRequired:
      "Please explicitly confirm your availability on Sunday 17/01/2027 before submitting your application.",
    errorImageConsentRequired:
      "Attending the event involves general photo and video coverage. Without your agreement on this point, we unfortunately cannot accept your application.",
    errEmailInUse:
      "This email address already has an account. Sign in above or use \"Forgot password\" with this email address.",
    errInvalidEmail: "The email address provided is not valid.",
    errMissingPassword: "The password is missing.",
    errWeakPassword: "The password must contain at least 6 characters.",
    errNetworkFailed: "Account creation failed due to a network issue. Please try again in a moment.",
    errPermissionDenied: "Account creation was denied by the Firestore access rules.",
    errServiceUnavailable: "The registration service is temporarily unavailable. Please try again later.",
    errGenericWithMessage: "The application could not be saved: {message}",
    errGenericNoMessage:
      "The application could not be saved. Check the required fields or use a different email if an account already exists.",
    adminVolPageTitle: "Volunteer management",
    adminVolPageSubtitle:
      "Working view to review applications, assign a role, and distinguish Sunday meeting presence from support around the event.",
    statusReceived: "Application received",
    statusReceivedDesc: "The person applied, or a role was assigned internally but the email hasn't gone out yet.",
    statusAssigned: "Assigned",
    statusAssignedDesc: "The role has been assigned and the email sent — awaiting the person's confirmation.",
    statusInformed: "Informed",
    statusConfirmed: "Confirmed",
    statusConfirmedDesc: "Marked manually by the team (e.g. after a phone call). Sends no email.",
    statusCancelledLabel: "Cancelled / withdrew",
    statusCancelledDesc: "The person is no longer participating; their role and assignment are removed. Sends no email.",
    statusCancelled: "Cancelled",
    statusPendingGuardianApproval: "Awaiting parental approval",
    tabMeetingVolunteers: "Meeting volunteers",
    tabAssignedPosts: "Assigned posts",
    tabMeetingSupport: "Support around the meeting",
    tabAlerts: "Alerts",
    panelTitleAllAssignedPosts: "All assigned posts",
    panelTitleAlerts: "Assignment alerts",
    meetingViewSubtitle: "Filter applications and assign each person to the right role directly.",
    panelSubtitleAssignedPosts:
      "Compact spreadsheet-style view with one row per assigned post to quickly filter, review and adjust assignments.",
    panelSubtitleAlerts: "History of withdrawals, assignment removals and badges to watch operationally.",
    panelSubtitleSupport:
      "Follow here the people available before or after the meeting for setup, prep or logistics help.",
    searchLabel: "Search",
    searchPlaceholder: "Name, email, role...",
    statusFilterLabel: "Application status",
    allLabel: "All",
    unassignedSectionTitle: "Unassigned applications",
    unassignedSectionDesc:
      "These volunteers received the automatic application confirmation and account creation email. Next step is to assign them internally.",
    colVolunteer: "Volunteer",
    colContact: "Contact",
    colLanguages: "Languages",
    colStatus: "Status",
    colRoleToAssign: "Role to assign",
    colMission: "Mission",
    chooseRoleOption: "Choose a role",
    chooseRoleToAdd: "Choose a role to add",
    emptyUnassigned: "No pending application at the moment.",
    accountMailSent: "Account + email sent",
    accountMailPending: "To send",
    assignedSectionTitle: "Assigned or being informed",
    assignedSectionDesc:
      "The internal assignment is saved right away. The email is a separate notification step: until it's sent, the person simply still needs to be informed.",
    selectAll: "Select all",
    selectNeedsInfo: "Select those to inform",
    deselectAll: "Deselect all",
    sendingInProgress: "Sending...",
    sendToSelected: "Send to {count} selected",
    emptyAssigned: "No volunteer assigned at the moment.",
    emptySupport: "No volunteer available around the meeting at the moment.",
    emptyPosts: "No post to show at the moment.",
    emptyAlerts: "No assignment alert recorded at the moment.",
    addRoleButton: "+ Add a role",
    confirmAction: "Confirm",
    cancelAction: "Cancel / withdraw",
    reactivateAction: "Reactivate application",
    sendAssignmentEmail: "Send assignment email",
    alreadyInformed: "✓ Already informed",
    alreadyInformedTooltip: "This person has already been told about their role{date}. Click to resend the email if needed.",
    statusBadgeTooltip:
      "This status follows from the actions below (role assigned, email sent) — it doesn't change directly, except to confirm or cancel.",
    initialAssignmentLabel: "Initial assignment: {role}.",
    lastMailSentLabel: "Last assignment email sent on {date} (role: {role}).",
    editFunctionTooltip: "Edit function",
    primaryRoleTitle: "{role} (main role)",
    editFunctionAria: "Edit {name}'s function for {role}",
    removeRoleAria: "Remove the {role} role from {name}",
    removeRoleTitle: "Remove {role}",
    ageUnit: "years old",
    statedPreferences: "Stated preferences",
    noPreferenceStated: "None stated",
    volunteerDetailClose: "Close",
    volunteerDetailContact: "Contact",
    volunteerDetailLanguages: "Languages",
    volunteerDetailMeetingRole: "Meeting role",
    volunteerDetailSunday: "Sunday meeting",
    volunteerDetailSupport: "Support around the meeting",
    volunteerNotAssigned: "Not assigned",
    showMoreButton: "Show 10 more",
    languageLabel: "Language",
    langEn: "EN",
    langFr: "FR",
    langDe: "DE",
    volunteerFallbackLabel: "Volunteer",
    assignmentsEyebrow: "Volunteer space",
    assignmentsTitle: "My assignments",
    assignmentsSubtitle:
      "Find your position here as soon as it's assigned, along with useful information to help you prepare.",
    assignmentsLoading: "Loading your assignments...",
    assignmentsMissionsPanelTitle: "My missions",
    assignmentsMissionsPanelSubtitle: "All your volunteer assignments in one place.",
    assignmentsMissionEyebrow: "Mission",
    assignmentsMissionIntro: "All the information below relates to this mission and belongs together.",
    assignmentsMissionFallbackTitle: "My mission",
    assignmentsMissionPanelSubtitle: "What you need to know for this role.",
    assignmentsTeamLabel: "Team",
    assignmentsFunctionLabel: "Function",
    assignmentsShiftLabel: "Shift",
    assignmentsStatusLabel: "Status",
    assignmentsToBeConfirmed: "To be confirmed",
    assignmentsCoordinationPanelTitle: "Team pointers",
    assignmentsCoordinationPanelSubtitle: "Read-only view of coordination information.",
    assignmentsTeamLeadLabel: "Team lead",
    assignmentsContactLabel: "Contact",
    assignmentsBriefingLabel: "Briefing",
    assignmentsInstructionsLabel: "Instructions",
    assignmentsInstructionsFallback: "Instructions will be shared here.",
    assignmentsTeamPanelTitle: "My team",
    assignmentsTeamPanelSubtitle: "Current composition of the team linked to this assignment.",
    assignmentsColumnName: "Name",
    assignmentsColumnFunction: "Function",
    assignmentsColumnContact: "Contact",
    assignmentsTeamUnavailable: "Composition not available",
    assignmentsDocumentsPanelTitle: "Team documents",
    assignmentsDocumentsPanelSubtitle: "Useful documents linked to this assignment.",
    assignmentsDocumentsEmpty: "No team document has been published yet for this assignment.",
    assignmentsEmptyPanelTitle: "My assignments",
    assignmentsEmptyPanelSubtitle: "Your assignment isn't available yet.",
    assignmentsEmptyParagraph1:
      "You don't have a role assigned yet for this edition. Our team is currently finalising volunteer assignments and you'll be informed of your position by December 10 at the latest.",
    assignmentsEmptyParagraph2:
      "As soon as it's confirmed, your position will appear here with useful information for your mission. Thank you for your patience and your commitment.",
    documentsEyebrow: "Volunteer space",
    documentsTitle: "My documents",
    documentsSubtitle: "Briefings, maps, procedures and useful information accessible based on your assignment.",
    documentsUploadInvoicePanelTitle: "Submit an invoice",
    documentsUploadInvoicePanelSubtitle:
      "Submit an invoice related to the current edition here. It will automatically appear in the budget for review.",
    documentsAvailablePanelTitle: "Available documents",
    documentsLoading: "Loading documents...",
    documentsColumnTitle: "Title",
    documentsColumnTeam: "Team",
    documentsColumnOpen: "View",
    documentsCertificateTitle: "Certificate of Participation",
    documentsCertificateGenerate: "Generate",
    documentsCertificateUnavailable: "Not available yet",
    documentsOpenAria: "Open {title}",
    documentsEmptyWithTeam: "No document available",
    documentsEmptyNoTeam: "No global document available",
    documentsPendingAssignment: "Awaiting assignment",
    documentsCertificateReadyNote: "Your participation certificate is now available. You can generate it whenever you need it.",
    documentsCertificatePendingNote:
      "Your participation certificate will become available after your departure has been recorded by your team lead or by the welcome desk.",
    documentsInvoicesPanelTitle: "My invoices",
    documentsInvoicesPanelSubtitle: "Find the invoices you've submitted here along with their budget review status.",
    documentsColumnInvoice: "Invoice",
    documentsColumnEdition: "Edition",
    documentsColumnStatus: "Review status",
    documentsNoInvoice: "No invoice submitted",
    documentsOpenButtonFallback: "Open",
    navSectionOverview: "Overview",
    navSectionVolunteers: "Volunteers",
    navSectionAccreditations: "Accreditations",
    navSectionPreprogram: "Pre-programme",
    navSectionWebsite: "Website",
    navSectionSettings: "Settings",
    navSectionMyAccess: "My access",
    navSectionAthletePortal: "Athlete Portal",
    navSectionStatistics: "Statistics",
    navDashboard: "Dashboard",
    navDocuments: "Documents",
    navBudget: "Budget",
    navVolunteersLink: "Volunteers",
    navTeamsAndPosts: "Teams & positions",
    navAttendance: "Attendance",
    navAccreditationVolunteers: "Volunteers",
    navAccreditationJudges: "Judges",
    navPress: "Press",
    navVip: "VIP",
    navPreprogramU12U14: "U12 / U14",
    navPreprogramBasketCarrier: "Basket carrier",
    navWebsiteOverviewAdmin: "Overview",
    navWebsiteOverviewManager: "Website — overview",
    navWebsiteEdition: "Current edition",
    navWebsiteEmagazine: "E-magazine",
    navWebsiteNews: "News",
    navWebsitePartners: "Partners",
    navWebsitePressReleases: "Press releases",
    navRolesAccess: "Roles & access",
    navInvitations: "Invitations",
    navMyProfile: "My profile",
    navOverview: "Overview",
    navMyTeam: "My team",
    navMyVolunteerFile: "My volunteer file",
    navMyAssignments: "My assignments",
    navMyDocuments: "My documents",
    navMyChildren: "My children",
    navAthleteTransport: "Athlete transport",
    navMyTransports: "My transport shifts",
    navAthletes: "Athletes",
    navPortalSettings: "Portal settings",
    navAthleteRegistry: "Athlete registry",
    navMeetingResults: "Meeting results",
    navMeetingRecords: "Meeting records",
    navHallOfWinners: "Hall of Winners",
    roleLabelAdmin: "Administrator",
    roleLabelBudget: "Budget",
    roleLabelManager: "Manager",
    roleLabelTeamLead: "Team lead",
    roleLabelVolunteer: "Volunteer",
    roleLabelParentU14: "U14 parent",
    roleLabelWebsiteManager: "Website manager",
    roleLabelAthleteTransportLead: "Athlete transport lead",
    roleLabelAthleteTransportVolunteer: "Athlete transport shuttle",
    roleLabelMeetingDirector: "Meeting director",
    shellMenuLabel: "Menu",
    shellBackToSite: "Back to the public site",
    shellTagline: "Team and event access platform.",
    shellCollapse: "Collapse",
    shellActiveEditionLabel: "Active edition",
    shellLogout: "Log out",
    shellCloseMenuAria: "Close the menu",
    shellReopenMenuAria: "Reopen the menu",
    shellCloseLabel: "Close",
    shellViewAsLabel: "View as",
    shellAdminViewHint: "Simplified admin view: one menu per domain, without mixing journeys.",
    shellAccessDeniedTitle: "Limited access",
    dashboardNoAssignmentYet: "No assignment confirmed yet",
    dashboardBriefingToBeConfirmed: "Briefing to be confirmed",
    dashboardTemplateConfiguration: "template configuration",
    dashboardEditionWord: "edition",
    dashboardClosed: "closed",
    dashboardEditionSaving: "Saving the edition...",
    dashboardEditionUpdated: "Active edition updated",
    dashboardEditionSwitchFailed: "Switching edition failed.",
    dashboardPrioritiesTitle: "My priorities",
    dashboardAdminPrioritiesSubtitle: "The decisions and actions to take today.",
    dashboardLoadingApplications: "Loading volunteer applications...",
    dashboardAdminApplicationsToProcess: "{count} volunteer application(s) to process",
    dashboardLoadingTeams: "Loading team composition...",
    dashboardAdminIncompleteTeams: "{count} team(s) still incomplete to secure",
    dashboardLoadingDocuments: "Loading documents...",
    dashboardAdminDocumentsToReview: "{count} document(s) published to review or share",
    dashboardLoadingU14Requests: "Loading U14 requests...",
    dashboardAdminU14RequestsToFollow: "{count} pre-programme request(s) received to follow up",
    dashboardQuickAccessTitle: "Quick access",
    dashboardAdminQuickAccessSubtitle: "Direct entries to the management modules.",
    dashboardManageVolunteers: "Manage volunteers",
    dashboardManageRoles: "Manage roles",
    dashboardAdjustTeams: "Adjust teams",
    dashboardProduceBadges: "Produce badges",
    dashboardManageWebsite: "Manage the website",
    dashboardManageAthletes: "Manage athletes",
    dashboardManageResults: "Manage results",
    dashboardVolunteerPrioritiesSubtitle: "The essentials to be ready on meeting day.",
    dashboardLoadingAssignment: "Loading your assignment...",
    dashboardCurrentAssignment: "Current assignment",
    dashboardPlannedShift: "Planned shift",
    dashboardVolunteerFileStatus: "Volunteer file status",
    dashboardLoadingMissionDocuments: "Loading mission documents...",
    dashboardDocumentsAvailableForTeams: "{count} document(s) available for your teams",
    dashboardBriefingLabel: "Briefing",
    dashboardVolunteerDepartureReminder: "After your mission, remember to tell your team lead you're leaving so your certificate can be unlocked.",
    dashboardVolunteerQuickAccessSubtitle: "Find your volunteer screens in one click.",
    dashboardManagerPrioritiesSubtitle: "Welcome desk and coordination follow-up for the day.",
    dashboardManagerTaskCheckIn: "Check in arrivals at the volunteer desk and hand out badge + t-shirt",
    dashboardManagerTaskLunch: "Track the lunch sandwich collection at midday",
    dashboardManagerTaskAttendance: "Update attendance and departure times with team leads",
    dashboardManagerQuickAccessSubtitle: "Operational tools for the volunteer desk.",
    dashboardParentPrioritiesSubtitle: "The next things to follow up for my children.",
    dashboardNoU14Request: "No U14 request linked to this account yet.",
    dashboardParentQuickAccessSubtitle: "All the parent follow-up centralised in one place.",
    dashboardParentConfirmedPending: "{confirmed} request(s) confirmed, {pending} still pending.",
    dashboardTeamLeadPrioritiesSubtitle: "What to track to keep the team running.",
    dashboardOpenPositions: "{count} position(s) still open in {roles}",
    dashboardAllTeamsFull: "All your teams have reached their planned headcount",
    dashboardLoadingAssignments: "Loading assignments...",
    dashboardTeamMembersCount: "{count} member(s) currently attached to your teams",
    dashboardLoadingTeamDocuments: "Loading team documents...",
    dashboardTeamDocumentsAvailable: "{count} team document(s) already available",
    dashboardLoadingReplacements: "Loading substitutes...",
    dashboardReplacementsIdentified: "{count} substitute(s) currently identified",
    dashboardTeamLeadDepartureReminder: "Before a volunteer leaves, remember to record their departure so their certificate becomes available.",
    dashboardTeamLeadQuickAccessSubtitle: "Coordination tools for team leads.",
    dashboardWelcome: "Welcome",
    dashboardIntro: "Your account centralises your active modules and opens the right journeys based on your profile.",
    dashboardActiveEditionTitle: "Active edition",
    dashboardActiveEditionSubtitle: "New volunteer and pre-programme applications are linked to this edition.",
    dashboardSwitchEdition: "Switch edition",
    dashboardSwitchEffectTitle: "Effect of the switch",
    dashboardSwitchEffectSubtitle: "What the platform will do immediately after the change.",
    dashboardSwitchEffectAccounts: "Existing accounts remain intact in `users`.",
    dashboardSwitchEffectRoles: "Roles and support tasks serve as a base to prepare the next edition.",
    dashboardSwitchEffectVolunteerModule: "The volunteer module becomes empty again for the new edition until a new file is filled in.",
    dashboardSwitchEffectPreprogram: "Pre-programme registrations restart from zero on the new edition.",
    dashboardSwitchEffectClosedEdition: "If you move to a more recent edition, the edition you're leaving is marked as closed.",
    dashboardSwitchEffectArchivedData: "Past editions' data remains stored and can be consulted by switching back.",
    dashboardInstallTitle: "Add MyCLIM to your phone",
    dashboardInstallIntro: "Keep MyCLIM at hand like a real app, right from your home screen.",
    dashboardInstallInstructionsAria: "Installation instructions",
    dashboardInstallOnIphone: "On iPhone",
    dashboardInstallIphoneSteps: "Open MyCLIM in Safari, tap Share then choose Add to Home Screen.",
    dashboardInstallOnAndroid: "On Android",
    dashboardInstallAndroidSteps: "Open MyCLIM in Chrome, tap the menu then choose Add to Home screen.",
    dashboardInstallNote: "You'll be able to launch MyCLIM in one tap, like a regular app.",
    dashboardVolunteerFileSubtitle: "Find here the status of your application and the information you submitted.",
    dashboardOpenMyFile: "Open my file",
    dashboardToComplete: "To complete",
    dashboardAvailabilityLabel: "Availability",
    dashboardWhatYouCanDoTitle: "What you can do here",
    dashboardWhatYouCanDoBody: "Review your application, update some answers and keep your volunteer information up to date without recreating an account.",
    dashboardJoinVolunteersTitle: "Want to join the volunteers too?",
    dashboardJoinVolunteersSubtitle: "Your parent space stays active, and you can add the volunteer journey to the same account.",
    dashboardBecomeVolunteer: "Become a volunteer",
    dashboardJoinVolunteersPoint1: "A single account to follow your children and your volunteer missions",
    dashboardJoinVolunteersPoint2: "Access afterwards to volunteer assignments, documents and accreditations",
    dashboardJoinVolunteersPoint3: "The volunteer application stays independent from your U14 parent module",
    dashboardTargetEdition: "Target edition",
    dashboardCurrentlyVisibleEdition: "Edition currently visible in the app",
    dashboardLoadingGeneric: "Loading...",
    dashboardPreprogramOpening: "Pre-programme opening",
    authLoadingEyebrow: "Loading",
    authLoadingTitle: "Opening MyCLIM",
    authLoadingBody: "We're restoring your session and your access.",
    accessDeniedMessage: "You don't have the rights to open this page. You've been redirected to an authorised space.",
    invoiceClassified: "Classified",
    invoiceToClassify: "To classify",
    invoiceAddFileFirst: "Add the invoice file first.",
    invoiceSaving: "Saving the invoice...",
    invoiceSavedLinked: "Invoice submitted and linked to a budget line.",
    invoiceSavedUnlinked: "Invoice submitted. It's ready to be classified.",
    invoiceSaveFailed: "Submitting the invoice failed.",
    invoiceTitleLabel: "Title",
    invoiceTitlePlaceholder: "Hotel, meal, transport invoice...",
    invoiceFileLabel: "File",
    invoiceUploadLabel: "Submit an invoice",
    invoiceUploadHelper: "PDF or image — the file is stored then linked to the budget",
    invoiceExpenseLineLabel: "Budget line",
    invoiceClassifyLater: "Classify later",
    invoiceNoteLabel: "Note",
    invoiceNotePlaceholder: "Supplier reference, useful comment...",
    invoiceSubmitting: "Saving...",
    invoiceSubmitButton: "Submit the invoice",
    invoiceDefaultTitle: "Invoice",
    invoiceDetachAria: "Unlink {name}",
    invoiceDetachTitle: "Unlink the invoice",
  },
  fr: {
    myclim: "MyCLIM",
    returnHome: "Retour à l'accueil",
    loginPageTitle: "Espace bénévoles MyCLIM",
    loginPageSubtitle: "Connectez-vous pour retrouver vos affectations, vos documents, votre accréditation et toutes les informations utiles du meeting.",
    loginEyebrow: "Connexion",
    loginHeading: "Accéder à MyCLIM",
    loginEmailLabel: "Email",
    loginPasswordLabel: "Mot de passe",
    loginForgotPassword: "Mot de passe oublié",
    loginForgotPasswordLoading: "Envoi...",
    loginRememberMe: "Se souvenir de moi",
    loginRememberMeDescription: "Rester connecté sur cet appareil après fermeture du navigateur.",
    loginButton: "Se connecter",
    loginLoading: "Connexion...",
    loginError: "Connexion impossible. Vérifiez votre email et votre mot de passe.",
    loginResetSuccess: "Si un compte existe pour cette adresse, un email de réinitialisation vient d'être envoyé.",
    loginResetError: "Impossible d'envoyer le mail de réinitialisation pour le moment.",
    loginResetEmailRequired: "Indiquez d'abord votre adresse email pour recevoir le lien de réinitialisation.",
    loginVolunteerLink: "Devenir bénévole",
    loginPreprogramLink: "Inscrire un enfant au pré-programme",
    landingTopline: "CMCM Luxembourg Indoor Meeting",
    landingTitle: "MyCLIM - Toutes les informations sur le CMCM Luxembourg Indoor Meeting 2027",
    landingDescription:
      "Choisissez votre parcours pour accéder rapidement aux inscriptions, aux informations pratiques et à votre espace personnel.",
    landingLoginButton: "Se connecter",
    landingLoginHint: "Vous avez déjà un compte ? Accédez directement à votre espace personnel.",
    volunteersTitle: "Bénévoles",
    volunteersDescription: "Connexion, création de compte et candidature bénévole.",
    preprogramTitle: "Pré-programme U12/U14",
    preprogramDescription: "Accès parents et inscription au pré-programme et porte-panier.",
    volunteerPageTitle: "Bénévoles CMCM Luxembourg Indoor Meeting",
    volunteerPageSubtitle: "Connectez-vous à votre espace ou déposez votre candidature bénévole.",
    volunteerLoginEyebrow: "Connexion",
    volunteerLoginTitle: "J'ai déjà un compte",
    volunteerLoginDescription: "Connectez-vous pour retrouver vos affectations, documents et informations du meeting.",
    volunteerApplyEyebrow: "Candidature",
    volunteerApplyTitle: "Je candidate comme bénévole",
    volunteerApplyButton: "Candidater",
    volunteerCloseButton: "Fermer le questionnaire",
    volunteerPlaceholder: "Le questionnaire bénévole s'ouvrira ici, juste sous ce bloc.",
    preprogramPageTitle: "Inscription Pré-programme U12/U14 et porte-panier",
    preprogramPageSubtitle:
      "Inscrivez votre enfant au Pré-programme U12/U14 ou au rôle de porte-panier, puis retrouvez ensuite les statuts et informations pratiques dans votre espace parent.",
    preprogramIntroEyebrow: "U12 / U14 2027",
    preprogramIntroTitle: "Inscrire mon enfant au Pré-programme ou comme porte-panier",
    preprogramIntroDescription:
      "Le compte parent est créé en même temps que l'inscription. Pour chaque enfant, vous pouvez indiquer s'il souhaite participer au Pré-programme, au porte-panier, ou si vous acceptez l'une ou l'autre des deux possibilités selon les places disponibles.",
    preprogramClosedTitle: "Les inscriptions ouvriront le 10 novembre 2026 à 10h00",
    preprogramClosedDescription:
      "Le formulaire Pré-programme et porte-panier n'est pas encore ouvert. En attendant, cette page vous explique le fonctionnement des sélections et des confirmations.",
    preprogramClosedCardTitle: "Fonctionnement des acceptations pour l'édition 2027",
    preprogramClosedCardBody:
      "Pour l'édition 2027, la demande de votre enfant ne pourra être étudiée que si le dossier est complet. Pour les courses, les places sont attribuées dans l'ordre d'arrivée des dossiers complets, puis une liste d'attente s'applique une fois les quotas atteints. Le jour du meeting, chaque enfant ne pourra être confirmé que dans une seule activité. Si vous demandez à la fois le Pré-programme et le rôle de porte-panier, la confirmation finale ne sera donnée que pour une seule des deux options.",
    preprogramClosedRulesTitle: "Règles importantes à connaître",
    preprogramClosedRulesBody:
      "Chaque enfant ne pourra être confirmé que dans une seule activité le jour du meeting. Si une demande porte à la fois sur le Pré-programme et sur le porte-panier, la confirmation finale ne sera donnée que pour une seule des deux options.",
    preprogramClosedTimingTitle: "Ce qui se passera à l'ouverture",
    preprogramClosedTimingBody:
      "Le 10 novembre 2026 à 10h00, le formulaire deviendra automatiquement accessible sur cette même page. Vous pourrez alors créer le compte parent et envoyer la demande.",
    fieldFirstName: "Prénom",
    fieldLastName: "Nom",
    fieldGender: "Genre",
    fieldSelectPlaceholder: "Sélectionner",
    genderFemale: "Femme",
    genderMale: "Homme",
    otherLabel: "Autre",
    fieldTshirtSize: "Taille t-shirt",
    fieldEmail: "Email",
    fieldPhone: "Téléphone",
    fieldPassword: "Mot de passe",
    fieldConfirmPassword: "Confirmer le mot de passe",
    fieldBirthDate: "Date de naissance",
    under14Title: "Moins de 14 ans",
    under14Body:
      "Désolée, nous ne pouvons malheureusement pas prendre de bénévole de moins de 14 ans sauf pour le rôle de porte-panier dans la mesure des places disponibles.",
    minorTitle: "Bénévole mineur",
    minorBody:
      "Votre date de naissance indique un bénévole mineur. Un contact de responsable légal est obligatoire et devra valider l'autorisation par email.",
    adultTitle: "Candidature adulte",
    adultBody: "Vous pouvez poursuivre la candidature bénévole normale.",
    createParentAccountLink: "Créer un compte parent",
    guardianEyebrow: "Responsable légal",
    guardianHeading: "Validation obligatoire pour les 14-17 ans",
    guardianFirstNameLabel: "Prénom du responsable légal",
    guardianLastNameLabel: "Nom du responsable légal",
    guardianEmailLabel: "Email du responsable légal",
    guardianPhoneLabel: "Téléphone du responsable légal",
    languagesEyebrow: "Langues",
    languagesHeading: "Quelles langues parlez-vous ?",
    otherLanguageLabel: "Autre langue",
    lunexEyebrow: "LUNEX",
    lunexHeading: "Êtes-vous étudiant LUNEX ?",
    yesLabel: "Oui",
    noLabel: "Non",
    lunexProgramLabel: "Programme LUNEX",
    occupationLabel: "Profession / occupation",
    cmcmExperienceLabel: "Expérience au CMCM Luxembourg Indoor Meeting",
    otherVolunteerExperienceLabel: "Autre expérience bénévole",
    availabilityEyebrow: "Disponibilités",
    availabilityHeading: "Quand pouvez-vous être présent(e) ?",
    availabilityIntro:
      "Les briefings du matin sont obligatoires. Pour le meeting, nous avons besoin de bénévoles disponibles le dimanche 17/01/2027 de 9h30 à 19h00. Les horaires exacts seront confirmés plus tard, mais cette amplitude doit être considérée comme indispensable pour le jour du meeting. Toute aide avant l'événement est la bienvenue, et nous serions particulièrement reconnaissants pour les aides disponibles le lundi.",
    mandatorySundayTitle: "Dimanche 17/01/2027 obligatoire",
    mandatorySundayBody:
      "Disponibilité requise pour le briefing, la collation avant le meeting, l'ouverture des portes à 13h00 et la compétition de 16h à 19h00.",
    confirmSundayLabel: "Je confirme être disponible le dimanche 17/01/2027",
    confirmSundayBody:
      "J'ai bien compris que ma présence de 9h30 à 19h00 environ, briefing compris, est indispensable pour le jour du meeting.",
    availabilitySubnote:
      "Vous pouvez aussi nous indiquer ci-dessous si vous êtes disponible pour aider avant le meeting ou lors du rangement du lundi.",
    availabilityFridayMorning: "Avant-meeting - vendredi matin",
    availabilityFridayAfternoon: "Avant-meeting - vendredi après-midi",
    availabilitySaturdayMorning: "Avant-meeting - samedi matin",
    availabilitySaturdayAfternoon: "Avant-meeting - samedi après-midi",
    availabilityMondayAfterMeeting: "Après-meeting - lundi 9h-12h",
    missionPreferencesEyebrow: "Préférences de mission",
    missionPreferencesLabel: "Sur quelles missions aimerais-tu aider ?",
    missionPreferencesHint:
      "Tu peux en choisir plusieurs. Cela nous indique tes envies, mais ne garantit pas d'obtenir l'une de ces missions — l'équipe attribue les rôles selon les besoins réels de l'événement.",
    missionPreferencesUnavailable: "La liste des missions n'est pas encore disponible — tu pourras indiquer tes préférences plus tard depuis ton espace bénévole.",
    healthSafetyLabel: "Informations sécurité / santé",
    nextEditionTitle: "Édition suivante",
    nextEditionBody: "J'accepte d'être recontacté pour la prochaine édition.",
    imageRightsTitle: "Droit à l'image",
    imageRightsBody:
      "La présence sur l'événement implique des prises de vue photo et vidéo dans les espaces du meeting. Sans accord sur ce point, nous ne pourrons malheureusement pas retenir votre participation.",
    rgpdDisclaimer:
      "En envoyant ce formulaire, vous acceptez que vos données personnelles soient traitées par la Fédération Luxembourgeoise d'Athlétisme uniquement dans le cadre de votre inscription, de votre participation au CMCM Luxembourg Indoor Meeting et des communications associées.",
    submitApplicationButton: "Envoyer ma candidature",
    submittingLabel: "Envoi...",
    errorPasswordMismatch: "Les deux mots de passe ne correspondent pas.",
    errorSundayConfirmRequired:
      "Merci de confirmer explicitement votre présence le dimanche 17/01/2027 avant d'envoyer votre candidature.",
    errorImageConsentRequired:
      "La présence sur l'événement implique des prises de vue globales photo et vidéo. Sans accord sur ce point, nous ne pouvons malheureusement pas retenir votre candidature.",
    errEmailInUse:
      "Cette adresse a déjà un compte. Connectez-vous ci-dessus ou utilisez « Mot de passe oublié » avec cette adresse email.",
    errInvalidEmail: "L'adresse email indiquée n'est pas valide.",
    errMissingPassword: "Le mot de passe est manquant.",
    errWeakPassword: "Le mot de passe doit contenir au moins 6 caractères.",
    errNetworkFailed: "La création du compte a échoué à cause d'un problème réseau. Réessaie dans un instant.",
    errPermissionDenied: "La création du compte a été refusée par les règles d'accès Firestore.",
    errServiceUnavailable: "Le service d'inscription est momentanément indisponible. Réessaie plus tard.",
    errGenericWithMessage: "La candidature n'a pas pu être enregistrée : {message}",
    errGenericNoMessage:
      "La candidature n'a pas pu être enregistrée. Vérifiez les champs obligatoires ou utilisez un autre email si un compte existe déjà.",
    adminVolPageTitle: "Gestion des bénévoles",
    adminVolPageSubtitle:
      "Tableau de travail pour relire les candidatures, attribuer un poste et distinguer la présence meeting du dimanche de l'aide autour de l'événement.",
    statusReceived: "Candidature reçue",
    statusReceivedDesc: "La personne a postulé, ou un rôle lui a été attribué en interne mais l'email n'est pas encore parti.",
    statusAssigned: "Affecté",
    statusAssignedDesc: "Le rôle a été attribué et l'email envoyé — en attente de confirmation de la personne.",
    statusInformed: "Informé",
    statusConfirmed: "Confirmé",
    statusConfirmedDesc: "Marqué manuellement par l'équipe (ex : suite à un appel). N'envoie aucun email.",
    statusCancelledLabel: "Annulé / désisté",
    statusCancelledDesc: "La personne ne participe plus ; son rôle et son affectation sont retirés. N'envoie aucun email.",
    statusCancelled: "Annulé",
    statusPendingGuardianApproval: "Accord parental attendu",
    tabMeetingVolunteers: "Bénévoles - meeting",
    tabAssignedPosts: "Postes attribués",
    tabMeetingSupport: "Aide autour du meeting",
    tabAlerts: "Alertes",
    panelTitleAllAssignedPosts: "Tous les postes attribués",
    panelTitleAlerts: "Alertes affectations",
    meetingViewSubtitle: "Filtrez les candidatures puis affectez directement chaque personne au bon rôle.",
    panelSubtitleAssignedPosts:
      "Vue compacte de type tableur avec une ligne par poste attribué pour filtrer, relire et ajuster rapidement les affectations.",
    panelSubtitleAlerts: "Historique des désistements, retraits d'affectation et badges à surveiller côté opérationnel.",
    panelSubtitleSupport:
      "Suivez ici les personnes disponibles avant ou après le meeting pour le montage, la préparation ou l'aide logistique.",
    searchLabel: "Recherche",
    searchPlaceholder: "Nom, email, rôle...",
    statusFilterLabel: "Statut candidature",
    allLabel: "Tous",
    unassignedSectionTitle: "Candidatures reçues non affectées",
    unassignedSectionDesc:
      "Ces bénévoles ont reçu le mail automatique de confirmation de candidature et de création de compte. L'étape suivante consiste à les affecter en interne.",
    colVolunteer: "Bénévole",
    colContact: "Coordonnées",
    colLanguages: "Langues",
    colStatus: "Statut",
    colRoleToAssign: "Rôle à attribuer",
    colMission: "Mission",
    chooseRoleOption: "Choisir un rôle",
    chooseRoleToAdd: "Choisir un rôle à ajouter",
    emptyUnassigned: "Aucune candidature en attente pour le moment.",
    accountMailSent: "Compte + mail envoyés",
    accountMailPending: "À envoyer",
    assignedSectionTitle: "Bénévoles affectés ou en cours d'information",
    assignedSectionDesc:
      "L'affectation interne est enregistrée tout de suite. Le mail reste une étape de notification séparée : tant qu'il n'est pas parti, la personne reste simplement à informer.",
    selectAll: "Tout sélectionner",
    selectNeedsInfo: "Sélectionner à informer",
    deselectAll: "Désélectionner tout",
    sendingInProgress: "Envoi en cours...",
    sendToSelected: "Envoyer aux {count} sélectionné(s)",
    emptyAssigned: "Aucun bénévole affecté pour le moment.",
    emptySupport: "Aucun bénévole disponible autour du meeting pour le moment.",
    emptyPosts: "Aucun poste à afficher pour le moment.",
    emptyAlerts: "Aucune alerte d'affectation enregistrée pour le moment.",
    addRoleButton: "+ Ajouter un rôle",
    confirmAction: "Confirmer",
    cancelAction: "Annuler / désister",
    reactivateAction: "Réactiver la candidature",
    sendAssignmentEmail: "Envoyer l'email d'affectation",
    alreadyInformed: "✓ Personne déjà informée",
    alreadyInformedTooltip: "La personne a déjà été prévenue de son rôle{date}. Cliquer pour renvoyer l'email si besoin.",
    statusBadgeTooltip:
      "Ce statut découle des actions ci-dessous (rôle attribué, mail envoyé) — il ne se modifie pas directement, sauf confirmation ou annulation.",
    initialAssignmentLabel: "Affectation initiale : {role}.",
    lastMailSentLabel: "Dernier mail d'affectation envoyé le {date} (rôle : {role}).",
    editFunctionTooltip: "Modifier la fonction",
    primaryRoleTitle: "{role} (rôle principal)",
    editFunctionAria: "Modifier la fonction de {name} pour {role}",
    removeRoleAria: "Retirer le rôle {role} de {name}",
    removeRoleTitle: "Retirer {role}",
    ageUnit: "ans",
    statedPreferences: "Préférences indiquées",
    noPreferenceStated: "Aucune",
    volunteerDetailClose: "Fermer",
    volunteerDetailContact: "Contact",
    volunteerDetailLanguages: "Langues",
    volunteerDetailMeetingRole: "Rôle meeting",
    volunteerDetailSunday: "Meeting dimanche",
    volunteerDetailSupport: "Aide autour du meeting",
    volunteerNotAssigned: "Non attribué",
    showMoreButton: "Afficher 10 de plus",
    languageLabel: "Langue",
    langEn: "EN",
    langFr: "FR",
    langDe: "DE",
    volunteerFallbackLabel: "Bénévole",
    assignmentsEyebrow: "Espace bénévole",
    assignmentsTitle: "Mes affectations",
    assignmentsSubtitle:
      "Consulte ici ton poste dès qu'il te sera attribué, ainsi que les informations utiles pour bien te préparer.",
    assignmentsLoading: "Chargement de mes affectations...",
    assignmentsMissionsPanelTitle: "Mes missions",
    assignmentsMissionsPanelSubtitle: "Toutes tes affectations bénévoles visibles au même endroit.",
    assignmentsMissionEyebrow: "Mission",
    assignmentsMissionIntro: "Toutes les informations ci-dessous concernent cette mission et vont ensemble.",
    assignmentsMissionFallbackTitle: "Ma mission",
    assignmentsMissionPanelSubtitle: "Ce que je dois connaître pour ce poste.",
    assignmentsTeamLabel: "Équipe",
    assignmentsFunctionLabel: "Fonction",
    assignmentsShiftLabel: "Créneau",
    assignmentsStatusLabel: "Statut",
    assignmentsToBeConfirmed: "À confirmer",
    assignmentsCoordinationPanelTitle: "Repères équipe",
    assignmentsCoordinationPanelSubtitle: "Vue lecture seule des informations de coordination.",
    assignmentsTeamLeadLabel: "Chef d'équipe",
    assignmentsContactLabel: "Contact",
    assignmentsBriefingLabel: "Briefing",
    assignmentsInstructionsLabel: "Consignes",
    assignmentsInstructionsFallback: "Les consignes seront partagées ici.",
    assignmentsTeamPanelTitle: "Mon équipe",
    assignmentsTeamPanelSubtitle: "Composition actuelle de l'équipe liée à cette affectation.",
    assignmentsColumnName: "Nom",
    assignmentsColumnFunction: "Fonction",
    assignmentsColumnContact: "Contact",
    assignmentsTeamUnavailable: "Composition non disponible",
    assignmentsDocumentsPanelTitle: "Documents d'équipe",
    assignmentsDocumentsPanelSubtitle: "Documents utiles associés à cette affectation.",
    assignmentsDocumentsEmpty: "Aucun document d'équipe n'est encore publié pour cette affectation.",
    assignmentsEmptyPanelTitle: "Mes affectations",
    assignmentsEmptyPanelSubtitle: "Ton affectation n'est pas encore disponible pour le moment.",
    assignmentsEmptyParagraph1:
      "Tu n'as pas encore de rôle attribué sur cette édition. Notre équipe finalise actuellement les affectations bénévoles et tu seras informé(e) de ton poste au plus tard le 10 décembre.",
    assignmentsEmptyParagraph2:
      "Dès qu'il sera confirmé, ton poste apparaîtra ici avec les informations utiles pour ta mission. Merci pour ta patience et pour ton engagement à nos côtés.",
    documentsEyebrow: "Espace bénévole",
    documentsTitle: "Mes documents",
    documentsSubtitle: "Briefings, plans, procédures et infos utiles accessibles selon l'affectation.",
    documentsUploadInvoicePanelTitle: "Déposer une facture",
    documentsUploadInvoicePanelSubtitle:
      "Dépose ici une facture liée à l'édition en cours. Elle remontera automatiquement dans le budget pour classement.",
    documentsAvailablePanelTitle: "Documents disponibles",
    documentsLoading: "Chargement des documents...",
    documentsColumnTitle: "Titre",
    documentsColumnTeam: "Équipe",
    documentsColumnOpen: "Consultation",
    documentsCertificateTitle: "Certificat de participation",
    documentsCertificateGenerate: "Générer",
    documentsCertificateUnavailable: "Pas encore disponible",
    documentsOpenAria: "Ouvrir {title}",
    documentsEmptyWithTeam: "Aucun document disponible",
    documentsEmptyNoTeam: "Aucun document global disponible",
    documentsPendingAssignment: "En attente d'affectation",
    documentsCertificateReadyNote: "Ton certificat de participation est disponible. Tu peux le générer quand tu le souhaites.",
    documentsCertificatePendingNote:
      "Ton certificat de participation sera disponible une fois ton départ enregistré par ton chef d'équipe ou par l'accueil.",
    documentsInvoicesPanelTitle: "Mes factures",
    documentsInvoicesPanelSubtitle: "Retrouve ici les factures que tu as déposées et leur état de classement dans le budget.",
    documentsColumnInvoice: "Facture",
    documentsColumnEdition: "Édition",
    documentsColumnStatus: "Classement",
    documentsNoInvoice: "Aucune facture déposée",
    documentsOpenButtonFallback: "Ouvrir",
    navSectionOverview: "Vue générale",
    navSectionVolunteers: "Bénévoles",
    navSectionAccreditations: "Accréditations",
    navSectionPreprogram: "Pré-programme",
    navSectionWebsite: "Site web",
    navSectionSettings: "Réglages",
    navSectionMyAccess: "Mes accès",
    navSectionAthletePortal: "Athlete Portal",
    navSectionStatistics: "Statistiques",
    navDashboard: "Tableau de bord",
    navDocuments: "Documents",
    navBudget: "Budget",
    navVolunteersLink: "Bénévoles",
    navTeamsAndPosts: "Équipes & postes",
    navAttendance: "Présences",
    navAccreditationVolunteers: "Bénévoles",
    navAccreditationJudges: "Juges",
    navPress: "Presse",
    navVip: "VIP",
    navPreprogramU12U14: "U12 / U14",
    navPreprogramBasketCarrier: "Porte-panier",
    navWebsiteOverviewAdmin: "Vue d’ensemble",
    navWebsiteOverviewManager: "Site web — vue d'ensemble",
    navWebsiteEdition: "Édition courante",
    navWebsiteEmagazine: "E-magazine",
    navWebsiteNews: "Actualités",
    navWebsitePartners: "Partenaires",
    navWebsitePressReleases: "Communiqués presse",
    navRolesAccess: "Rôles & accès",
    navInvitations: "Invitations",
    navMyProfile: "Mon profil",
    navOverview: "Vue d'ensemble",
    navMyTeam: "Mon équipe",
    navMyVolunteerFile: "Mon dossier bénévole",
    navMyAssignments: "Mes affectations",
    navMyDocuments: "Mes documents",
    navMyChildren: "Mes enfants",
    navAthleteTransport: "Transport athlètes",
    navMyTransports: "Mes transports",
    navAthletes: "Athlètes",
    navPortalSettings: "Réglages portal",
    navAthleteRegistry: "Base athlètes",
    navMeetingResults: "Résultats meeting",
    navMeetingRecords: "Records meeting",
    navHallOfWinners: "Hall of Winners",
    roleLabelAdmin: "Administrateur",
    roleLabelBudget: "Budget",
    roleLabelManager: "Gestionnaire",
    roleLabelTeamLead: "Chef d’équipe",
    roleLabelVolunteer: "Bénévole",
    roleLabelParentU14: "Parent U14",
    roleLabelWebsiteManager: "Gestionnaire site",
    roleLabelAthleteTransportLead: "Transport athlètes",
    roleLabelAthleteTransportVolunteer: "Navettes athlètes",
    roleLabelMeetingDirector: "Direction meeting",
    shellMenuLabel: "Menu",
    shellBackToSite: "Retour au site public",
    shellTagline: "Plateforme équipes et accès meeting.",
    shellCollapse: "Replier",
    shellActiveEditionLabel: "Édition active",
    shellLogout: "Se déconnecter",
    shellCloseMenuAria: "Fermer le menu",
    shellReopenMenuAria: "Rouvrir le menu",
    shellCloseLabel: "Fermer",
    shellViewAsLabel: "Voir comme",
    shellAdminViewHint: "Vue admin simplifiée : un menu par domaine, sans mélanger les parcours.",
    shellAccessDeniedTitle: "Accès limité",
    dashboardNoAssignmentYet: "Aucune affectation confirmée pour l'instant",
    dashboardBriefingToBeConfirmed: "Briefing à confirmer",
    dashboardTemplateConfiguration: "configuration modèle",
    dashboardEditionWord: "édition",
    dashboardClosed: "clôturée",
    dashboardEditionSaving: "Sauvegarde de l'édition en cours...",
    dashboardEditionUpdated: "Édition active mise à jour",
    dashboardEditionSwitchFailed: "La bascule d'édition a échoué.",
    dashboardPrioritiesTitle: "Mes priorités",
    dashboardAdminPrioritiesSubtitle: "Les décisions et actions de pilotage à prendre aujourd'hui.",
    dashboardLoadingApplications: "Chargement des candidatures bénévoles...",
    dashboardAdminApplicationsToProcess: "{count} candidature(s) bénévole(s) à traiter",
    dashboardLoadingTeams: "Chargement de la composition des équipes...",
    dashboardAdminIncompleteTeams: "{count} équipe(s) encore incomplète(s) à sécuriser",
    dashboardLoadingDocuments: "Chargement des documents...",
    dashboardAdminDocumentsToReview: "{count} document(s) publiés à relire ou diffuser",
    dashboardLoadingU14Requests: "Chargement des demandes U14...",
    dashboardAdminU14RequestsToFollow: "{count} demande(s) d'inscription au pré-programme reçue(s) à suivre",
    dashboardQuickAccessTitle: "Accès rapides",
    dashboardAdminQuickAccessSubtitle: "Entrées directes vers les modules de pilotage.",
    dashboardManageVolunteers: "Gérer les bénévoles",
    dashboardManageRoles: "Gérer les rôles",
    dashboardAdjustTeams: "Ajuster les équipes",
    dashboardProduceBadges: "Produire les badges",
    dashboardManageWebsite: "Gérer le site internet",
    dashboardManageAthletes: "Gérer les athlètes",
    dashboardManageResults: "Gérer les résultats",
    dashboardVolunteerPrioritiesSubtitle: "L'essentiel pour être prêt le jour du meeting.",
    dashboardLoadingAssignment: "Chargement de ton affectation...",
    dashboardCurrentAssignment: "Affectation actuelle",
    dashboardPlannedShift: "Créneau prévu",
    dashboardVolunteerFileStatus: "Statut du dossier bénévole",
    dashboardLoadingMissionDocuments: "Chargement des documents de mission...",
    dashboardDocumentsAvailableForTeams: "{count} document(s) disponible(s) pour tes équipes",
    dashboardBriefingLabel: "Briefing",
    dashboardVolunteerDepartureReminder: "Après ta mission, pense à signaler ton départ à ton responsable pour débloquer ton certificat.",
    dashboardVolunteerQuickAccessSubtitle: "Retrouve tes écrans bénévoles en un clic.",
    dashboardManagerPrioritiesSubtitle: "Le suivi d'accueil et de coordination du jour J.",
    dashboardManagerTaskCheckIn: "Pointer les arrivées au guichet bénévoles et distribuer badge + tee-shirt",
    dashboardManagerTaskLunch: "Suivre la récupération des sandwichs à midi",
    dashboardManagerTaskAttendance: "Mettre à jour les présences et horaires de départ avec les chefs d'équipe",
    dashboardManagerQuickAccessSubtitle: "Outils opérationnels pour le guichet bénévoles.",
    dashboardParentPrioritiesSubtitle: "Les prochains éléments à suivre pour mes enfants.",
    dashboardNoU14Request: "Aucune demande U14 liée à ce compte pour l'instant.",
    dashboardParentQuickAccessSubtitle: "Tout le suivi parent centralisé dans un seul espace.",
    dashboardParentConfirmedPending: "{confirmed} demande(s) confirmée(s), {pending} encore en attente.",
    dashboardTeamLeadPrioritiesSubtitle: "Ce qu'il faut suivre pour faire tourner l'équipe.",
    dashboardOpenPositions: "{count} poste(s) encore ouvert(s) sur {roles}",
    dashboardAllTeamsFull: "Toutes tes équipes ont atteint leur effectif prévu",
    dashboardLoadingAssignments: "Chargement des affectations...",
    dashboardTeamMembersCount: "{count} membre(s) actuellement rattaché(s) à tes équipes",
    dashboardLoadingTeamDocuments: "Chargement des documents d'équipe...",
    dashboardTeamDocumentsAvailable: "{count} document(s) d'équipe déjà disponibles",
    dashboardLoadingReplacements: "Chargement des remplaçants...",
    dashboardReplacementsIdentified: "{count} remplaçant(s) actuellement identifié(s)",
    dashboardTeamLeadDepartureReminder: "Avant qu'un bénévole parte, pense à pointer son départ pour rendre son certificat disponible.",
    dashboardTeamLeadQuickAccessSubtitle: "Les outils de coordination chef d'équipe.",
    dashboardWelcome: "Bienvenue",
    dashboardIntro: "Ton compte centralise tes modules actifs et ouvre les bons parcours selon ton profil.",
    dashboardActiveEditionTitle: "Édition active",
    dashboardActiveEditionSubtitle: "Les nouvelles candidatures bénévoles et pré-programme sont rattachées à cette édition.",
    dashboardSwitchEdition: "Changer d'édition",
    dashboardSwitchEffectTitle: "Effet de la bascule",
    dashboardSwitchEffectSubtitle: "Ce que la plateforme fera immédiatement après changement.",
    dashboardSwitchEffectAccounts: "Les comptes existants restent intacts dans `users`.",
    dashboardSwitchEffectRoles: "Les rôles et tâches support servent de base pour préparer l'édition suivante.",
    dashboardSwitchEffectVolunteerModule: "Le module bénévole redevient vide pour la nouvelle édition tant qu'un nouveau dossier n'est pas rempli.",
    dashboardSwitchEffectPreprogram: "Les inscriptions pré-programme repartent de zéro sur la nouvelle édition.",
    dashboardSwitchEffectClosedEdition: "Si tu avances vers une édition plus récente, l'édition quittée est marquée comme clôturée.",
    dashboardSwitchEffectArchivedData: "Les données des anciennes éditions restent conservées en base et peuvent être consultées en rebasculant.",
    dashboardInstallTitle: "Ajoute MyCLIM à ton téléphone",
    dashboardInstallIntro: "Garde MyCLIM sous la main comme une vraie appli, directement depuis l'écran d'accueil.",
    dashboardInstallInstructionsAria: "Instructions d'installation",
    dashboardInstallOnIphone: "Sur iPhone",
    dashboardInstallIphoneSteps: "Ouvre MyCLIM dans Safari, touche Partager puis choisis Sur l'écran d'accueil.",
    dashboardInstallOnAndroid: "Sur Android",
    dashboardInstallAndroidSteps: "Ouvre MyCLIM dans Chrome, touche le menu puis choisis Ajouter à l'écran d'accueil.",
    dashboardInstallNote: "Tu pourras lancer MyCLIM en un clic, comme une application classique.",
    dashboardVolunteerFileSubtitle: "Retrouve ici l'état de ta candidature et les informations transmises.",
    dashboardOpenMyFile: "Ouvrir mon dossier",
    dashboardToComplete: "À compléter",
    dashboardAvailabilityLabel: "Disponibilités",
    dashboardWhatYouCanDoTitle: "Ce que tu peux faire ici",
    dashboardWhatYouCanDoBody: "Relire ta candidature, compléter certaines réponses et garder tes informations bénévoles à jour sans recréer un compte.",
    dashboardJoinVolunteersTitle: "Envie de rejoindre aussi les bénévoles ?",
    dashboardJoinVolunteersSubtitle: "Ton espace parent reste actif, et tu peux ajouter le parcours bénévole sur le même compte.",
    dashboardBecomeVolunteer: "Devenir bénévole",
    dashboardJoinVolunteersPoint1: "Un seul compte pour suivre tes enfants et tes missions bénévoles",
    dashboardJoinVolunteersPoint2: "Accès ensuite aux affectations, documents et accréditations bénévoles",
    dashboardJoinVolunteersPoint3: "La candidature bénévole reste indépendante de ton module parent U14",
    dashboardTargetEdition: "Édition cible",
    dashboardCurrentlyVisibleEdition: "Édition actuellement visible dans l'application",
    dashboardLoadingGeneric: "Chargement...",
    dashboardPreprogramOpening: "Ouverture pré-programme",
    authLoadingEyebrow: "Chargement",
    authLoadingTitle: "Ouverture de MyCLIM",
    authLoadingBody: "Nous restaurons votre session et vos accès.",
    accessDeniedMessage: "Vous n'avez pas les droits pour ouvrir cette page. Vous avez été redirigé vers un espace autorisé.",
    invoiceClassified: "Classée",
    invoiceToClassify: "À classer",
    invoiceAddFileFirst: "Ajoute d'abord le fichier de facture.",
    invoiceSaving: "Enregistrement de la facture...",
    invoiceSavedLinked: "Facture déposée et liée à une ligne de dépense.",
    invoiceSavedUnlinked: "Facture déposée. Elle est prête à être classée.",
    invoiceSaveFailed: "Le dépôt de la facture a échoué.",
    invoiceTitleLabel: "Titre",
    invoiceTitlePlaceholder: "Facture hôtel, repas, transport...",
    invoiceFileLabel: "Fichier",
    invoiceUploadLabel: "Déposer une facture",
    invoiceUploadHelper: "PDF ou image · le fichier est stocké puis relié au budget",
    invoiceExpenseLineLabel: "Ligne de dépense",
    invoiceClassifyLater: "À classer plus tard",
    invoiceNoteLabel: "Note",
    invoiceNotePlaceholder: "Référence fournisseur, commentaire utile...",
    invoiceSubmitting: "Enregistrement...",
    invoiceSubmitButton: "Déposer la facture",
    invoiceDefaultTitle: "Facture",
    invoiceDetachAria: "Délier {name}",
    invoiceDetachTitle: "Délier la facture",
  },
  de: {
    myclim: "MyCLIM",
    returnHome: "Zur Startseite",
    loginPageTitle: "MyCLIM Freiwilligenbereich",
    loginPageSubtitle: "Melden Sie sich an, um Ihre Einsätze, Dokumente, Akkreditierung und alle nützlichen Meeting-Informationen abzurufen.",
    loginEyebrow: "Anmeldung",
    loginHeading: "Zugang zu MyCLIM",
    loginEmailLabel: "E-Mail",
    loginPasswordLabel: "Passwort",
    loginForgotPassword: "Passwort vergessen",
    loginForgotPasswordLoading: "Wird gesendet...",
    loginRememberMe: "Angemeldet bleiben",
    loginRememberMeDescription: "Nach dem Schließen des Browsers auf diesem Gerät angemeldet bleiben.",
    loginButton: "Anmelden",
    loginLoading: "Anmelden...",
    loginError: "Anmeldung fehlgeschlagen. Bitte überprüfen Sie Ihre E-Mail und Ihr Passwort.",
    loginResetSuccess: "Falls ein Konto für diese Adresse existiert, wurde soeben eine Zurücksetzen-E-Mail gesendet.",
    loginResetError: "Die Zurücksetzen-E-Mail konnte derzeit nicht gesendet werden.",
    loginResetEmailRequired: "Bitte geben Sie zuerst Ihre E-Mail-Adresse ein, um den Zurücksetzen-Link zu erhalten.",
    loginVolunteerLink: "Freiwilliger werden",
    loginPreprogramLink: "Ein Kind für das Vorprogramm anmelden",
    landingTopline: "CMCM Luxembourg Indoor Meeting",
    landingTitle: "MyCLIM - Alle Informationen zum CMCM Luxembourg Indoor Meeting 2027",
    landingDescription:
      "Wählen Sie Ihren Zugang, um Registrierungen, praktische Informationen und Ihren persönlichen Bereich schnell zu erreichen.",
    landingLoginButton: "Anmelden",
    landingLoginHint: "Sie haben bereits ein Konto? Gehen Sie direkt zu Ihrem persönlichen Bereich.",
    volunteersTitle: "Freiwillige",
    volunteersDescription: "Anmelden, Konto erstellen oder sich als Volunteer bewerben.",
    preprogramTitle: "U12/U14 Vorprogramm",
    preprogramDescription: "Elternzugang und Anmeldung für Vorprogramm und Korbträger.",
    volunteerPageTitle: "Freiwillige des CMCM Luxembourg Indoor Meeting",
    volunteerPageSubtitle: "Melden Sie sich an oder reichen Sie Ihre Volunteer-Bewerbung ein.",
    volunteerLoginEyebrow: "Anmeldung",
    volunteerLoginTitle: "Ich habe bereits ein Konto",
    volunteerLoginDescription: "Melden Sie sich an, um Einsätze, Dokumente und Meeting-Infos zu sehen.",
    volunteerApplyEyebrow: "Bewerbung",
    volunteerApplyTitle: "Ich möchte Volunteer werden",
    volunteerApplyButton: "Bewerben",
    volunteerCloseButton: "Formular schließen",
    volunteerPlaceholder: "Das Volunteer-Formular wird hier direkt unter diesem Abschnitt angezeigt.",
    preprogramPageTitle: "Anmeldung Vorprogramm U12/U14 und Korbträger",
    preprogramPageSubtitle:
      "Melden Sie Ihr Kind für das U12/U14-Vorprogramm oder die Korbträger-Rolle an und verfolgen Sie danach alles im Elternbereich.",
    preprogramIntroEyebrow: "U12 / U14 2027",
    preprogramIntroTitle: "Mein Kind für das Vorprogramm oder als Korbträger anmelden",
    preprogramIntroDescription:
      "Das Elternkonto wird während der Anmeldung erstellt. Für jedes Kind können Sie angeben, ob es am Vorprogramm teilnehmen, Korbträger sein oder je nach Verfügbarkeit für beide Optionen berücksichtigt werden soll.",
    preprogramClosedTitle: "Die Anmeldungen öffnen am 10. November 2026 um 10:00 Uhr",
    preprogramClosedDescription:
      "Das Formular für Vorprogramm und Korbträger ist noch nicht geöffnet. Bis dahin erklärt diese Seite, wie Auswahl und Bestätigung funktionieren.",
    preprogramClosedCardTitle: "So laufen die Zusagen für die Ausgabe 2027 ab",
    preprogramClosedCardBody:
      "Für die Ausgabe 2027 kann die Anmeldung Ihres Kindes nur berücksichtigt werden, wenn das Dossier vollständig ist. Für die Läufe werden die Plätze in der Reihenfolge des Eingangs vollständiger Anmeldungen vergeben, danach gilt eine Warteliste. Am Tag des Meetings kann jedes Kind nur für eine Aktivität bestätigt werden. Wenn Sie sowohl das Vorprogramm als auch die Korbträger-Rolle anfragen, wird die endgültige Bestätigung nur für eine der beiden Optionen erteilt.",
    preprogramClosedRulesTitle: "Wichtige Regeln vor der Öffnung",
    preprogramClosedRulesBody:
      "Jedes Kind kann am Tag des Meetings nur für eine Aktivität bestätigt werden. Wenn eine Anfrage sowohl Vorprogramm als auch Korbträger betrifft, wird die endgültige Bestätigung nur für eine der beiden Optionen erteilt.",
    preprogramClosedTimingTitle: "Was am Eröffnungstag passiert",
    preprogramClosedTimingBody:
      "Am 10. November 2026 um 10:00 Uhr wird das Formular automatisch auf dieser Seite freigeschaltet. Dann können Sie das Elternkonto erstellen und die Anfrage absenden.",
    fieldFirstName: "Vorname",
    fieldLastName: "Nachname",
    fieldGender: "Geschlecht",
    fieldSelectPlaceholder: "Auswählen",
    genderFemale: "Weiblich",
    genderMale: "Männlich",
    otherLabel: "Andere",
    fieldTshirtSize: "T-Shirt-Größe",
    fieldEmail: "E-Mail",
    fieldPhone: "Telefon",
    fieldPassword: "Passwort",
    fieldConfirmPassword: "Passwort bestätigen",
    fieldBirthDate: "Geburtsdatum",
    under14Title: "Unter 14 Jahre",
    under14Body:
      "Leider können wir keine Freiwilligen unter 14 Jahren aufnehmen, außer für die Rolle als Korbträger, je nach Verfügbarkeit.",
    minorTitle: "Minderjähriger Freiwilliger",
    minorBody:
      "Ihr Geburtsdatum weist auf einen minderjährigen Freiwilligen hin. Ein Kontakt zum Erziehungsberechtigten ist verpflichtend und muss die Genehmigung per E-Mail bestätigen.",
    adultTitle: "Erwachsenenbewerbung",
    adultBody: "Sie können mit der regulären Freiwilligenbewerbung fortfahren.",
    createParentAccountLink: "Elternkonto erstellen",
    guardianEyebrow: "Erziehungsberechtigter",
    guardianHeading: "Verpflichtende Zustimmung für 14- bis 17-Jährige",
    guardianFirstNameLabel: "Vorname des Erziehungsberechtigten",
    guardianLastNameLabel: "Nachname des Erziehungsberechtigten",
    guardianEmailLabel: "E-Mail des Erziehungsberechtigten",
    guardianPhoneLabel: "Telefon des Erziehungsberechtigten",
    languagesEyebrow: "Sprachen",
    languagesHeading: "Welche Sprachen sprechen Sie?",
    otherLanguageLabel: "Andere Sprache",
    lunexEyebrow: "LUNEX",
    lunexHeading: "Sind Sie LUNEX-Student(in)?",
    yesLabel: "Ja",
    noLabel: "Nein",
    lunexProgramLabel: "LUNEX-Studiengang",
    occupationLabel: "Beruf / Tätigkeit",
    cmcmExperienceLabel: "Erfahrung beim CMCM Luxembourg Indoor Meeting",
    otherVolunteerExperienceLabel: "Andere Freiwilligenerfahrung",
    availabilityEyebrow: "Verfügbarkeit",
    availabilityHeading: "Wann können Sie anwesend sein?",
    availabilityIntro:
      "Die Morgen-Briefings sind verpflichtend. Für das Meeting benötigen wir Freiwillige, die am Sonntag, den 17.01.2027, von 9:30 bis 19:00 Uhr verfügbar sind. Die genauen Zeiten werden später bestätigt, aber dieser Zeitraum sollte für den Tag des Meetings als unverzichtbar betrachtet werden. Jede Hilfe vor der Veranstaltung ist willkommen, und wir wären besonders dankbar für Hilfe am Montag.",
    mandatorySundayTitle: "Sonntag, 17.01.2027, verpflichtend",
    mandatorySundayBody:
      "Verfügbarkeit erforderlich für das Briefing, den Imbiss vor dem Meeting, die Türöffnung um 13:00 Uhr und den Wettkampf von 16 bis 19 Uhr.",
    confirmSundayLabel: "Ich bestätige, dass ich am Sonntag, den 17.01.2027, verfügbar bin",
    confirmSundayBody:
      "Mir ist bewusst, dass meine Anwesenheit von etwa 9:30 bis 19:00 Uhr, Briefing inbegriffen, für den Tag des Meetings unverzichtbar ist.",
    availabilitySubnote:
      "Sie können uns unten auch mitteilen, ob Sie vor dem Meeting oder beim Aufräumen am Montag helfen können.",
    availabilityFridayMorning: "Vor dem Meeting - Freitagmorgen",
    availabilityFridayAfternoon: "Vor dem Meeting - Freitagnachmittag",
    availabilitySaturdayMorning: "Vor dem Meeting - Samstagmorgen",
    availabilitySaturdayAfternoon: "Vor dem Meeting - Samstagnachmittag",
    availabilityMondayAfterMeeting: "Nach dem Meeting - Montag 9-12 Uhr",
    missionPreferencesEyebrow: "Einsatzpräferenzen",
    missionPreferencesLabel: "Bei welchen Einsätzen möchtest du gerne helfen?",
    missionPreferencesHint:
      "Sie können mehrere auswählen. Das zeigt uns Ihre Wünsche, garantiert aber nicht einen dieser Einsätze — das Team vergibt die Rollen nach dem tatsächlichen Bedarf der Veranstaltung.",
    missionPreferencesUnavailable: "Die Liste der Einsätze ist noch nicht verfügbar — Sie können Ihre Präferenzen später in Ihrem Freiwilligenbereich angeben.",
    healthSafetyLabel: "Sicherheits-/Gesundheitsinformationen",
    nextEditionTitle: "Nächste Ausgabe",
    nextEditionBody: "Ich bin damit einverstanden, für die nächste Ausgabe kontaktiert zu werden.",
    imageRightsTitle: "Bildrechte",
    imageRightsBody:
      "Die Teilnahme an der Veranstaltung beinhaltet Foto- und Videoaufnahmen in den Bereichen des Meetings. Ohne Ihre Zustimmung dazu können wir Ihre Teilnahme leider nicht berücksichtigen.",
    rgpdDisclaimer:
      "Mit dem Absenden dieses Formulars stimmen Sie zu, dass Ihre personenbezogenen Daten von der Luxemburgischen Leichtathletikföderation ausschließlich im Rahmen Ihrer Anmeldung, Ihrer Teilnahme am CMCM Luxembourg Indoor Meeting und damit verbundener Kommunikation verarbeitet werden.",
    submitApplicationButton: "Bewerbung absenden",
    submittingLabel: "Wird gesendet...",
    errorPasswordMismatch: "Die beiden Passwörter stimmen nicht überein.",
    errorSundayConfirmRequired:
      "Bitte bestätigen Sie ausdrücklich Ihre Verfügbarkeit am Sonntag, den 17.01.2027, bevor Sie Ihre Bewerbung absenden.",
    errorImageConsentRequired:
      "Die Teilnahme an der Veranstaltung beinhaltet allgemeine Foto- und Videoaufnahmen. Ohne Ihre Zustimmung dazu können wir Ihre Bewerbung leider nicht berücksichtigen.",
    errEmailInUse:
      "Diese E-Mail-Adresse hat bereits ein Konto. Melden Sie sich oben an oder nutzen Sie „Passwort vergessen“ mit dieser E-Mail-Adresse.",
    errInvalidEmail: "Die angegebene E-Mail-Adresse ist ungültig.",
    errMissingPassword: "Das Passwort fehlt.",
    errWeakPassword: "Das Passwort muss mindestens 6 Zeichen enthalten.",
    errNetworkFailed: "Die Kontoerstellung ist aufgrund eines Netzwerkproblems fehlgeschlagen. Bitte versuchen Sie es gleich noch einmal.",
    errPermissionDenied: "Die Kontoerstellung wurde durch die Firestore-Zugriffsregeln verweigert.",
    errServiceUnavailable: "Der Registrierungsdienst ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.",
    errGenericWithMessage: "Die Bewerbung konnte nicht gespeichert werden: {message}",
    errGenericNoMessage:
      "Die Bewerbung konnte nicht gespeichert werden. Überprüfen Sie die Pflichtfelder oder verwenden Sie eine andere E-Mail-Adresse, falls bereits ein Konto besteht.",
    languageLabel: "Sprache",
    langEn: "EN",
    langFr: "FR",
    langDe: "DE",
  },
};

function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window === "undefined") return "en";

    const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return supportedLanguages.includes(storedLanguage) ? storedLanguage : "en";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    }
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key) => messages[language]?.[key] ?? messages.en[key] ?? key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

function LanguageSwitch() {
  const { language, setLanguage, t } = useLanguage();

  return (
    <div className="language-switch" aria-label={t("languageLabel")}>
      {supportedLanguages.map((option) => (
        <button
          key={option}
          className={`language-switch__button ${language === option ? "language-switch__button--active" : ""}`}
          type="button"
          onClick={() => setLanguage(option)}
        >
          {t(`lang${option[0].toUpperCase()}${option.slice(1)}`)}
        </button>
      ))}
    </div>
  );
}

export { LanguageProvider, LanguageSwitch };
